### ISSUE TITLE
Exception can't printdebugmsg Original bytes ...

### ISSUE THREAD

**Issue by ShhShadShh** [techiew/DirectX11Hook#1]
so do i need the original dxgi.dll together with the one i build in the same game folder or only the compiled one ? im also getting this exception do you know what this can be ? IMAGE(right click>open image in new tab to fullscreen it ) : https://imgur.com/a/EvGkC8f

**Comment by ShhShadShh** [comment]
i swapped hook( present ) with hook ( resize buffer) and Present went through but resize buffer still fails: https://imgur.com/a/1UuSGMT 

any idea what can be wrong with Hook(targetResizeBuffersFunction, &ResizeBuffers ????????

**Comment by ShhShadShh** [comment]
so i commented out the Hook(targetResizeBuffersFunction, &ResizeBuffers, function and now it works somewhat : https://imgur.com/a/rGMCXie still no idea whats wrong with Resizebuffer hook

**Comment by geometry88** [comment]
same problem, resize = crash

does anyone have a solution?

**Comment by geometry88** [comment]
The problem was solved by adding an input argument `IDXGISwapChain* pThis` to the function `ResizeBuffers` and `OnResizeBuffers`

**Comment by ShhShadShh** [comment]
> The problem was solved by adding an input argument `IDXGISwapChain* pThis` to the function `ResizeBuffers` and `OnResizeBuffers`

idk still doesn't work what am i doing wrong ? 
IMGUR > [imgur](https://imgur.com/a/InzHgcL)

**Comment by geometry88** [comment]
here too, and yes, I noticed that on different operating systems dxgi offsets are different ... maybe this is the problem
![Screenshot_20201127-210836](https://user-images.githubusercontent.com/16748478/100478782-eeb62500-30f4-11eb-92a2-0e16138a08ef.jpg)

**Comment by ShhShadShh** [comment]
> here too, and yes, I noticed that on different operating systems dxgi offsets are different ... maybe this is the problem

must be different dxgi offsets yeah...

**Comment by techiew** [comment]
Oh hey guys, I haven't received any email notification about this issue whatsoever, I just randomly stumbled on it right now. I remember @ShhShadShh from my Youtube comments tho.

It seems my signature scanning approach for finding the function addresses in dxgi is very unstable, the culprit is likely to be different versions of dxgi.dll, I've experienced firsthand that the function addresses can move around a bit after a Windows update. As for @geometry88's extra input argument for ResizeBuffers, I'll have to check in the documentation if they added a new argument or something. Thank you guys for your interest in my project.

I want to continue working on this project, it's not high priority right now, but I definitely want to look into it.

**Comment by techiew** [comment]
I did a massive rewrite and the hook now uses virtual method table hooking, so wrong offsets and stuff should no longer be an issue across different computers. If anyone still has problems then please post them in another issue.

cb20bb2ad5418cb1a17d8c3ce2f724b495e79642
